e2e tests: fix tests | add github workflow

diff --git a/tests/e2e/temp/traffic-job.yaml b/tests/e2e/temp/traffic-job.yaml
--- a/tests/e2e/temp/traffic-job.yaml
+++ b/tests/e2e/temp/traffic-job.yaml
@@ -19,7 +19,7 @@ spec:
           # Generate traffic every second
           while [ $(date +%s) -lt $END_TIME ]; do
             echo "Sending request at $(date)"
-            curl -s http://test-app.default.svc.cluster.local:80/ || echo "Request failed"
+            curl -s http://target-deployment.default.svc.cluster.local:80/ || echo "Request failed"
             sleep 1
           done
           
